package umkmOmahOmben;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lenovo
 */
public class login extends javax.swing.JFrame {

    public static String idPegawai;
    public static int level = 3;

//    private void setid() {
//      
//    }
//    private void setlevel() {
//        try {
//            Connection Connect = (Connection) koneksi.getKoneksi();
//            Statement stm = (Statement) Connect.createStatement();
//            String sql = "SELECT * FROM tbl_akun Where id_pegawai ='" + idPegawai + "'";
//            ResultSet rs = stm.executeQuery(sql);
//            while (rs.next()) {
//                level = rs.getInt("level");
//                System.out.println(rs.getInt("level"));
//            }
//
//        } catch (SQLException | ClassNotFoundException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//
//    }
    // deklarasi
    /**
     * Creates new form login
     */
    public login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pw = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tpass = new javax.swing.JTextField();
        bregister = new javax.swing.JButton();
        tusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lp = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        pw.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pw.setLocation(new java.awt.Point(400, 300));
        pw.setResizable(false);
        pw.setSize(new java.awt.Dimension(499, 193));
        pw.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("MASUKAN PASSWORD ADMIN");
        pw.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jButton3.setText("MASUK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pw.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 80, 30));

        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        pw.getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 240, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bregister.setBorder(null);
        bregister.setContentAreaFilled(false);
        bregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });
        getContentPane().add(bregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 170, 40));

        tusername.setBackground(new java.awt.Color(241, 240, 236));
        tusername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tusername.setBorder(null);
        tusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tusernameMouseClicked(evt);
            }
        });
        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 310, 40));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 170, 40));

        lp.setText("LUPA PASSWORD?");
        lp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lpMouseEntered(evt);
            }
        });
        getContentPane().add(lp, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 120, 20));

        tpassword.setBackground(new java.awt.Color(241, 240, 236));
        tpassword.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tpassword.setBorder(null);
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 330, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design5/login.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tusernameMouseClicked

    }//GEN-LAST:event_tusernameMouseClicked

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cekuser = null;
        String cekpw = null;

        try {
            Connection Connect = (Connection) koneksi.getKoneksi();
            Statement stm = (Statement) Connect.createStatement();
            String sql = "SELECT * FROM tbl_akun Where username ='" + tusername.getText() + "' AND password='" + tpassword.getText() + "'";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {

                idPegawai = (rs.getString("id_pegawai"));
                cekuser = rs.getString("username");
                cekpw = rs.getString("password");
                level = rs.getInt("level");

            }
            rs.close();
            stm.close();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        if (cekuser == null && cekpw == null) {

            String pesan = "username atau password salah";
            JOptionPane.showMessageDialog(null, pesan);
            tpassword.setText("");
        } else {
            String pesan1 = "login Berhasil";
            JOptionPane.showMessageDialog(null, pesan1);
            new dashboard().setVisible(true);
            dispose();

        }
        System.out.println(idPegawai + " " + level + " login");
//        setid();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_tpasswordActionPerformed

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        pw.setVisible(true);
    }//GEN-LAST:event_bregisterActionPerformed

    private void lpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpMouseEntered

    }//GEN-LAST:event_lpMouseEntered

    private void lpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpMouseClicked
        dispose();
        new lupaPassword().setVisible(true);

    }//GEN-LAST:event_lpMouseClicked

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_tpassActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String sql = "select * from tbl_akun where level = '0' and password ='" + tpass.getText() + "'";
            Connection conn = (Connection) koneksi.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            System.out.println(sql);
            if (rs.next()) {
                new registrasi().setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(this, "PASSWORD SALAH");
                tpass.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage() + ", pada tombol registrasi");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bregister;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lp;
    private javax.swing.JFrame pw;
    private javax.swing.JTextField tpass;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
