/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umkmOmahOmben;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author Lenovo
 */
public class registrasi extends javax.swing.JFrame {

    private String idpegawai;
    private int level = 2;

    private void clear() {

        tusername.setText("");
        tpassword.setText("");
//        ID_PEGAWAI();
    }

    private void pilihanPegawai() {
        try {
            String sql = "select * from tbl_pegawai where 1";
            Connection con = (Connection) koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                pilgay.addItem(rs.getString("id_pegawai") + " || " + rs.getString("nama_pegawai"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

//    private void ID_PEGAWAI() {
//
//        String sql = "SELECT max(right(id_pegawai,4)) as id FROM tbl_pegawai ";
//        //mengambil nilai id pegawai dari kanan 4 huruf/angka
//        try {
//
//            Connection conn = (Connection) koneksi.getKoneksi();
//            java.sql.Statement stm = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
//            java.sql.ResultSet rs = stm.executeQuery(sql);
//            while (rs.next()) {
//
//                rs.last();
//                int autoid = rs.getInt("id");
//                String nomor = String.valueOf(autoid + 1);
//                int no = nomor.length();
//
//                for (int i = 0; i < 4 - no; i++) {
//                    nomor = "0" + nomor;
//                }
//                idpegawai = ("PG" + nomor);
//                System.out.println(idpegawai);
//
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//
//    }
    /**
     * Creates new form registrasi
     */
    public registrasi() {
        initComponents();
        pilihanPegawai();
//        ID_PEGAWAI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tusername = new javax.swing.JTextField();
        pilgay = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpassword.setBorder(null);
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 340, 40));

        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 180, 50));

        tusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tusername.setBorder(null);
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 340, 40));

        getContentPane().add(pilgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 340, 40));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design5/register.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = pilgay.getSelectedItem().toString().substring(0,6);
            System.out.println(id);
            String lvl = String.valueOf(level);
            String sql = "insert into `tbl_akun` VALUES ('" + id + "','" + tusername.getText() + "','" + tpassword.getText() + "','" + lvl + "')";
            java.sql.Connection con = (Connection) koneksi.getKoneksi();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Penympanan berhasil!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage() + " insert pegawai");
        }

        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> pilgay;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
