/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umkmOmahOmben;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lenovo
 */
public class registrasi extends javax.swing.JFrame {

    private String idpegawai;
    private int level = 2;

    private void clear() {

        tnama.setText("");
        tpassword.setText("");
        tnotlp.setText("");
        tusername.setText("");
        talamat.setText("");
//        ID_PEGAWAI();
    }

    private void ID_PEGAWAI() {
//        List logBarang = new ArrayList();
        String sql = "SELECT max(right(id_pegawai,4)) as id FROM tbl_pegawai ";
        //mengambil nilai id pegawai dari kanan 4 huruf/angka
        try {

            Connection conn = (Connection) koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            java.sql.ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    idpegawai = "PG0001";
                } else {
                    rs.last();
                    int autoid = rs.getInt("id");
                    String nomor = String.valueOf(autoid + 1);
                    int no = nomor.length();

                    for (int i = 0; i < 4 - no; i++) {
                        nomor = "0" + nomor;
                    }
                    idpegawai = ("PG" + nomor);
                    System.out.println(idpegawai);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * Creates new form registrasi
     */
    public registrasi() {
        initComponents();
        ID_PEGAWAI();
//        ID_PEGAWAI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tnama = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tusername = new javax.swing.JTextField();
        tnotlp = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpassword.setBorder(null);
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 340, 40));

        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 180, 50));

        tnama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnama.setBorder(null);
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 340, 40));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 60));

        tusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tusername.setBorder(null);
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 340, 40));

        tnotlp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnotlp.setBorder(null);
        tnotlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnotlpKeyTyped(evt);
            }
        });
        getContentPane().add(tnotlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 340, 40));

        talamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        talamat.setBorder(null);
        getContentPane().add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design5/register pegawai.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tnama.getText().equals("") || talamat.getText().equals("") || tnotlp.getText().equals("") || tusername.getText().length() < 6
                ||  tpassword.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "LENGKAPI DATA TERLEBIH DAHULU");
        } else {

            try {

                String lvl = String.valueOf(level);
                String sql = "INSERT INTO tbl_pegawai VALUES ('" + idpegawai + "','"
                        + tnama.getText() + "','" + tnotlp.getText() + "','" + talamat.getText() + "')";
                String sql1 = "insert into `tbl_akun` VALUES ('" + idpegawai + "','" + tnama.getText() + "','" + tpassword.getText() + "','" + lvl + "')";

                java.sql.Connection con = (Connection) koneksi.getKoneksi();
                PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();

                PreparedStatement ps = con.prepareStatement(sql1);
                ps.execute();

                JOptionPane.showMessageDialog(null, "Penympanan berhasil!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } catch (ClassNotFoundException ex) {
                
                Logger.getLogger(registrasi.class.getName()).log(Level.SEVERE, null, ex);
            }

            clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tnotlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnotlpKeyTyped
if(Character.isAlphabetic(evt.getKeyChar())){
    evt.consume();
}
if(tnotlp.getText().length() > 15){
    evt.consume();
}
    // TODO add your handling code here:
    }//GEN-LAST:event_tnotlpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnotlp;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
